[project]
name = "zenn-topic-suggester"
dynamic = ["version"]
description = "Zennの記事に設定する最適なトピックを検索するCLIツール"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "northward", email= "196759132+northward1@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.33.0",
    "numpy>=2.5.3",
    "onnxruntime>=1.30.0",
    "pandas>=3.0.6",
    "transformers>=5.17.0",
]
keywords = ["zenn", "cli"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Natural Language :: Japanese",
]

[project.urls]
Homepage = "https://github.com/northward1/zenn-topic-suggester"
Repository = "https://github.com/northward1/zenn-topic-suggester"
Issues = "https://github.com/northward1/zenn-topic-suggester/issues"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
zenn-topic-suggest = "zenn_topic_suggester:main"
